### ISSUE TITLE
chongxie.txt这个脚本开启后美团外卖右下角的购物车也会跟着消失了

### ISSUE THREAD

**Issue by linxiazhixi** [fmz200/wool_scripts#1]
https://raw.githubusercontent.com/fmz200/wool_scripts/main/QuantumultX/rewrite/chongxie.txt
这个脚本开启后美团外卖右下角的购物车也会跟着消失了

**Comment by fmz200** [comment]
> https://raw.githubusercontent.com/fmz200/wool_scripts/main/QuantumultX/rewrite/chongxie.txt 这个脚本开启后美团外卖右下角的购物车也会跟着消失了

好的，我已经反馈给张军了
