### ISSUE TITLE
百度地图-搜索"美食"后,美食频道里面的商品点击没反应,改全局直连也不行(内嵌的大众点评)

### ISSUE THREAD

**Issue by HyperQi** [fmz200/wool_scripts#17]
1. 【问题概述】：百度地图-搜索"美食"后，里面的美食商品点击没反应（嵌套的大众点评），大众点评的订单详情白屏，改全局直连也不行
2. 【APP】：Quantumlt X+百度地图商店最新版
3. 【复现流程】：百度地图-搜索“美食”，进入美食频道后，中间“限时秒杀”的“商品”点击没反应。列表页中的美食，点进去二级页面中的商品点击也没反应。
4. 【尝试解决】：抓包+看网络活动，又尝试加了一些美团/大众的Direct规则后，仍然无效，Reject的一些域名改为Direct也无效
5. 【备选方案】：**关闭圈X，重启百度地图，恢复正常，但是再次开启圈X一段时间后，问题依旧**
6. 【PS】：因为百度地图 x美团/大众 联合搞活动，每天都有优惠券领，很实惠。不想每次打开百度地图都关闭圈X，太繁琐了。

**Comment by fmz200** [comment]
没用过百度地图和大众点评，你可以在hostname中加上`-*.baidu.com`取消百度地图的MITM试试

**Comment by HyperQi** [comment]
谢谢，解决了。另外请教下，"－主机名" 和 "新增一个DIRECT的主机地址的 规则"这两个有什么区别？

**Comment by fmz200** [comment]
> 谢谢，解决了。另外请教下，"－主机名" 和 "新增一个DIRECT的主机地址的 规则"这两个有什么区别？

“-主机名”是重写用的，表示不对这个主机mitm，"新增一个DIRECT的主机地址”是分流用的，表示这个主机不走代理直接连接
