### ISSUE TITLE
花小猪打车

### ISSUE THREAD

**Issue by svngxr** [fmz200/wool_scripts#20]
https://raw.githubusercontent.com/fmz200/wool_scripts/main/QuantumultX/rewrite/cleanup.snippet

异常规则：^https://api.hongyibo.com.cn reject-dict

问题描述：花小猪打车时价格查询走了这个API地址，导致显示(网络错误/价格获取失败)而无法打车，微信小程序

**Comment by fmz200** [comment]
> https://raw.githubusercontent.com/fmz200/wool_scripts/main/QuantumultX/rewrite/cleanup.snippet
> 
> 异常规则：^https://api.hongyibo.com.cn reject-dict
> 
> 问题描述：花小猪打车时价格查询走了这个API地址，导致显示(网络错误/价格获取失败)而无法打车，微信小程序

已删除，更新即可
