### ISSUE TITLE
chongxie文件对于哔哩哔哩的稍后在看板块的消失

### ISSUE THREAD

**Issue by rkmy** [fmz200/wool_scripts#25]
自哔哩哔哩更新后重写文件对于哔哩哔哩的我的界面处的稍后再看板块没有显示了，
已确认升级为最新的chongxie.txt,，哔哩哔哩版本为7.54.0(75400100)，quanX版本：1.4.2-817。
![IMG_1462](https://github.com/fmz200/wool_scripts/assets/38809548/bd8dbfe5-a496-4e23-b81e-006b42456320)

**Comment by rkmy** [comment]
已更新解决

**Comment by fmz200** [comment]
OK
