### ISSUE TITLE
请求🙏 加入 Snapchat 和 Arena of valor 的图标

### ISSUE THREAD

**Issue by a994849598** [fmz200/wool_scripts#26]

**Comment by fmz200** [comment]
Arena of valor 是啥软件

**Comment by a994849598** [comment]
> Arena of valor 是啥软件

是一款游戏   国际版的“王者荣耀”

**Comment by fmz200** [comment]
都加了，王者荣耀用的国内版图片

Vincentor ***@***.***>於 2023年11月14日 週二，09:48寫道：
