### ISSUE TITLE
 请问拼多多果园抓取的AccessToken

### ISSUE THREAD

**Issue by XXXGITHUB777** [fmz200/wool_scripts#3]
填写在哪里呢？谢谢

<sub>Sent from <a href="https://apps.apple.com/cn/app/id1314212521">PPHub</a></sub>

**Comment by fmz200** [comment]
> 填写在哪里呢？谢谢
> 
> Sent from [PPHub](https://apps.apple.com/cn/app/id1314212521)

AccessToken存到boxjs里面了，如果你是用quanX在手机上跑定时任务就直接运行脚本，如果是在青龙上跑就添加到环境变量里面，脚本里面有说明，仔细看看

**Comment by XXXGITHUB777** [comment]
在qx上提示 
🔔多多果园, 开始!
共找到1 个CK
[Exception]: Can't find variable: require

进入果园提示token获取成功，在boxjs搜索Accesstoken也有同样的数据，不知道怎么办了

**Comment by fmz200** [comment]
> 在qx上提示 🔔多多果园, 开始! 共找到1 个CK [Exception]: Can't find variable: require
> 
> 进入果园提示token获取成功，在boxjs搜索Accesstoken也有同样的数据，不知道怎么办了

原作者已经不维护了，暂时不能用

**Comment by fmz200** [comment]
> 在qx上提示 🔔多多果园, 开始! 共找到1 个CK [Exception]: Can't find variable: require
> 
> 进入果园提示token获取成功，在boxjs搜索Accesstoken也有同样的数据，不知道怎么办了

经过我的测试，在quanX上暂时不能跑了，建议放到青龙上跑，并且token已经从AccessToken改成了PDDAccessToken。
