### ISSUE TITLE
talkatone重写没有效果

### ISSUE THREAD

**Issue by mottzz87** [fmz200/wool_scripts#40]
surge下使用 QX的这个重写脚本 https://github.com/fmz200/wool_scripts/blob/main/QuantumultX/rewrite/chongxie.txt 无效，
转换后的地址http://script.hub/file/_start_/https://raw.githubusercontent.com/fmz200/wool_scripts/main/QuantumultX/rewrite/chongxie.txt/_end_/chongxie.sgmodule?type=qx-rewrite&target=surge-module&del=true

大佬可以抽空看一下吗

**Comment by fmz200** [comment]
哪个规则无效？

mottzz87 ***@***.***>於 2024年3月13日 週三，02:03寫道：

**Comment by fmz200** [comment]
> surge下使用 QX的这个重写脚本 https://github.com/fmz200/wool_scripts/blob/main/QuantumultX/rewrite/chongxie.txt 无效， 转换后的地址http://script.hub/file/_start_/https://raw.githubusercontent.com/fmz200/wool_scripts/main/QuantumultX/rewrite/chongxie.txt/_end_/chongxie.sgmodule?type=qx-rewrite&target=surge-module&del=true
> 
> 大佬可以抽空看一下吗

这个规则放到QX上也不好使

**Comment by mottzz87** [comment]
> > surge下使用 QX的这个重写脚本 https://github.com/fmz200/wool_scripts/blob/main/QuantumultX/rewrite/chongxie.txt 无效， 转换后的地址http://script.hub/file/_start_/https://raw.githubusercontent.com/fmz200/wool_scripts/main/QuantumultX/rewrite/chongxie.txt/_end_/chongxie.sgmodule?type=qx-rewrite&target=surge-module&del=true
> > 大佬可以抽空看一下吗
> 
> 这个规则放到QX上也不好使

那怎么说，老哥，可以去广告吗

**Comment by fmz200** [comment]
> > > surge下使用 QX的这个重写脚本 https://github.com/fmz200/wool_scripts/blob/main/QuantumultX/rewrite/chongxie.txt 无效， 转换后的地址http://script.hub/file/_start_/https://raw.githubusercontent.com/fmz200/wool_scripts/main/QuantumultX/rewrite/chongxie.txt/_end_/chongxie.sgmodule?type=qx-rewrite&target=surge-module&del=true
> > > 大佬可以抽空看一下吗
> > 
> > 
> > 这个规则放到QX上也不好使
> 
> 那怎么说，老哥，可以辛苦搞一搞让它支持去广告吗

目前还没有抓到广告，不好抓
