### ISSUE TITLE
请更新天天基金重写规则

### ISSUE THREAD

**Issue by scyrte** [fmz200/wool_scripts#5]
# > 天天基金
^https?:\/\/j5\.dfcfw\.com\/WG\/**conf**\/202[0-9]{5}/.*.(jpg|png) url reject-200

^https?:\/\/j5\.dfcfw\.com\/WG\/**appconf**\/202[0-9]{5}/.*.(jpg|png) url reject-200

现有广告规则有开屏漏网之鱼，请合并以上两条规则，谢谢。

**Comment by fmz200** [comment]
> 

已更新
