### ISSUE TITLE
chongxie.txt 上汽大众app无法正常使用

### ISSUE THREAD

**Issue by k1suke** [fmz200/wool_scripts#59]
启用后多个页面内容无法加载，麻烦看看啦

**Comment by fmz200** [comment]
我没有这个APP，你可以自己看看有没有匹配这条重写
<img width="936" alt="image" src="https://github.com/fmz200/wool_scripts/assets/57740735/07531c63-67b4-4432-a585-63256ff0e28c">

**Comment by k1suke** [comment]
抱歉回复没看见！

<img width="313" alt="QQ20240429-113046@2x" src="https://github.com/fmz200/wool_scripts/assets/49939669/d598b68c-c6ab-4316-873d-e4a70e7c170c">
看起来像是禁止mitm了？

**Comment by fmz200** [comment]
> 抱歉回复没看见！
> 
> 
> 
> <img width="313" alt="QQ20240429-113046@2x" src="https://github.com/fmz200/wool_scripts/assets/49939669/d598b68c-c6ab-4316-873d-e4a70e7c170c">
> 
> 看起来像是禁止mitm了？

看样子是的，明天我排除一下吧
