### ISSUE TITLE
重写里面的字节跳动规则要删除了，圈X日志里会猛跳MitM错误信息

### ISSUE THREAD

**Issue by 1076764805** [fmz200/wool_scripts#6]
![941a6cca5416350306e1a8c2e99bc9a](https://user-images.githubusercontent.com/51862286/219844197-2ba98fdd-d5f7-4100-b1cf-d93d1b2ab982.jpg)

**Comment by fmz200** [comment]
> ![941a6cca5416350306e1a8c2e99bc9a](https://user-images.githubusercontent.com/51862286/219844197-2ba98fdd-d5f7-4100-b1cf-d93d1b2ab982.jpg)

已删除
