### ISSUE TITLE
chongxie文件对哔哩哔哩的净化会好使，但是过几分钟后就不好使了。已确认升级为最新的chongxie.txt,，哔哩哔哩版本为7.77.0(77700100)，quanX版本：1.5.0-830。

### ISSUE THREAD

**Issue by rkmy** [fmz200/wool_scripts#70]
最开始是这样的可以正常工作
![1](https://github.com/fmz200/wool_scripts/assets/38809548/3e14c171-4772-43c0-9e7e-0051c66100cc)
![2](https://github.com/fmz200/wool_scripts/assets/38809548/b6ee5f5b-63cc-42bb-832e-7cfc9e679f33)
但是从后台返回或者随便进入一个详情页之后，就会变成下图所示，就很神奇。
![3](https://github.com/fmz200/wool_scripts/assets/38809548/cdd6341f-a1a9-425c-b601-018ad8f21646)
就净化失效了，希望作者能告知是我做错了，还是有bug，希望得到指导，谢谢。

**Comment by fmz200** [comment]
再试试吧
