### ISSUE TITLE
可否修正斗鱼直播app里关注中的动态页内容被错误屏蔽的问题？

### ISSUE THREAD

**Issue by PaTTeeL** [fmz200/wool_scripts#83]
查了一下发现是这一条：
`^https?:\/\/rtbapi\.douyucdn\.cn\/japi\/sign\/app\/getinfo url reject-200`

改成 `^https?:\/\/rtbapi\.douyucdn\.cn\/japi\/sign\/app\/getinfo url reject-dict` 就可以了，

因为每次刷新远程内容都会覆盖本地修改，希望可以修复一下，感激不尽！

**Comment by fmz200** [comment]
已修复
