### ISSUE TITLE
懂车帝首页-热点-点击榜单中的内容白屏

### ISSUE THREAD

**Issue by AStoooooo** [fmz200/wool_scripts#92]
https://github.com/fmz200/wool_scripts/blob/f63dc9fba083c021292fce7c4e3db30a7e016a10/Loon/rule/rejectAd.list#L472
排查后发现是这条规则的问题，添加到本地直连后可正常浏览

我看这条是写在番茄小说app里的规则，在github搜索这个域名发现也有人说误杀的，大佬可看情况考虑删掉此规则
搜索结果链接：
https://github.com/search?q=bytegoofy.com&type=issues

**Comment by fmz200** [comment]
删掉了，字节系列的太容易误杀
