### ISSUE TITLE
loon 小红书去水印功能脚本在 surge 并不通用，请核实

### ISSUE THREAD

**Issue by frankk007** [fmz200/wool_scripts#95]
loon 小红书去水印功能脚本在 surge 并不通用，失效，请核实
loon quanx 的该脚本经过转写后，在surge 均表现失效

**Comment by fmz200** [comment]
> loon 小红书去水印功能脚本在 surge 并不通用，失效，请核实
> 
> loon quanx 的该脚本经过转写后，在surge 均表现失效

我这没问题，脚本配置都是通用的
