### ISSUE TITLE
投稿

### ISSUE THREAD

**Issue by fishdown** [fmz200/wool_scripts#98]
loon
高德地图
^https?:\/\/optimus-ads\.amap\.com\/uploadimg\/ reject  这个地址会让附近页面图标icon不显示
^https?:\/\/optimus-ads\.amap\.com\/uploadimg\/[a-zA-Z0-9]+\.gif reject-200
顺眼看到高德下面这个app
国家地理  现在改为 每日精选
http:\/\/dili\.sqcosmos\.com\/jiekou\/mains\/p\d+\.html response-body-json-jq '.album |= map(select(.id != "4154" and .id != "4165"))'
http:\/\/dili\.sqcosmos\.com\/jiekou\/endpage\/ad reject-dict
http不用hostname

**Comment by fmz200** [comment]
多谢，已经更新了

**Comment by fishdown** [comment]
> 多谢，已经更新了

http://dili\.sqcosmos\.com/jiekou/mains/p\d+\.html response-body-json-jq '.album |= map(select(.id != "4154" and .id != "4165" and .id != "3838"))'
这条需要更新一下，去除首页顶部广告
